### ISSUE TITLE
Error when run demo

### ISSUE THREAD

**Issue by babman92** [kendallb/PrintHtml#1]
Hi, i follow guide at https://stackoverflow.com/questions/3934508/printing-a-formatted-html-page-in-c-sharp
When i set:
info.Arguments = $"-p \"{printer}\" \"-l 0\" \"-t 0\" \"-r 0\" \"-b 0\" \"{string.Join("\" \"", urls)}\"";
I get a error: HTML page failed to load
If i just write: info.Arguments = $"-p \"{printer}\" \"{string.Join("\" \"", urls)}\"";
Print normal
Please help me, i want set content margin to print, thank in advance.

**Comment by kendallb** [comment]
Try this:

info.Arguments = $"-l 0 -t 0 -r 0 -b 0 -p \"{printer}\" \"{string.Join("\" \"", urls)}\"";

**Comment by babman92** [comment]
Many thanks :+1: 
I got it.
