### ISSUE TITLE
Orientation is not working

### ISSUE THREAD

**Issue by aitldeveloper** [kendallb/PrintHtml#15]
Hello,

We are thankful to you for this wonderful utility...

If I pass values for orientation it is not taking.

PrintHtml.exe -p "\\192.168.120.156\HP LaserJet Professional M1136 MFP (Copy 1)" -l 0 -t 0 -r 0 -b 0 -a "A5" -o "Portrait" URL

I tried without quote also but somehow when a portrait is given it is showing "Failed to load HTML"

**Comment by kendallb** [comment]
The default is portrait mode so the only orientation supported as optional is landscape.
