### ISSUE TITLE
using PrintHtml in windows servives .net

### ISSUE THREAD

**Issue by majkiBDG** [kendallb/PrintHtml#4]
Hi
If it's posible to use PrintHtml in windows services, because all error msg are interactive like :
```
QMessageBox msgBox;
msgBox.setWindowTitle("Fatal Error");
```
mayby it could drop msg to txt file or sth like that.

Thx,

**Comment by kendallb** [comment]
Unfortunately I was not able to figure out how to make this run as a console app, because it uses Windows services to execute. So I am not entirely sure if it can even be executed from within a windows service?
